stages:
  - test
  - build
  - release
  - publish

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

test:
  stage: test
  image: golang:1.15-alpine
  script:
    - apk add --update gcc libc-dev
    - wget -O /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64"
    - chmod +x /usr/local/bin/yq
    - go test -v ./cmd/x509-exporter

build:
  stage: build
  image: docker:stable-dind
  script:
    - echo "Logging to GitLab Container Registry with CI credentials..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build --tag $IMAGE_TAG .
    - docker push $IMAGE_TAG

semantic-release:
  stage: release
  image: enix/semantic-release:gitlab
  only:
    - master
  except:
    - tags
  script:
    - semantic-release --ci

publish-docker-hub:
  stage: publish
  only:
    refs:
      - /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/
  image: docker:stable
  script:
    - echo "Logging to GitLab Container Registry with CI credentials..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $DOCKER_HUB_REPOSITORY/$CI_PROJECT_NAME:${CI_COMMIT_REF_NAME:1}
    - echo "Logging to Docker Hub Registry with Enix credentials..."
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    - echo "Push release $CI_COMMIT_REF_NAME ..."
    - docker push $DOCKER_HUB_REPOSITORY/$CI_PROJECT_NAME:${CI_COMMIT_REF_NAME:1}
